build:
  command: npm run build:production
  publish: .next
  environment:
    NODE_VERSION: 20.19.5
    NEXT_PUBLIC_FIREBASE_API_KEY: demo-api-key
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: demo-project.firebaseapp.com
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: demo-project
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: demo-project.appspot.com
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 123456789
    NEXT_PUBLIC_FIREBASE_APP_ID: 1:123456789:web:demo
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: G-DEMO
  git:
    clone_args: ["--filter=blob:none", "https://github.com/Harsh-s-sharma/harshsharmaqa"]